# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'OpenSSL', '~> 1.0'

target 'InAppExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InAppExample

end
